### ISSUE TITLE
Prepare for public release

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/knowledgebase-public#3]
DONE:
. license add

TODO:
. rename to 'knowledgebase-public'
. remove sensitive docs relating to product function
. create private vs public policy discussion

DEPENDENCY:
. get final feedback for [proposition in discussion #60](https://github.com/interlock-network/interlock-kb/discussions/60#discussioncomment-2561196)

**Comment by Treevuhh** [comment]
This has been made public during the dev team meeting on Monday 5/16.
